### ISSUE TITLE
add more code.

### ISSUE THREAD

**Issue by astalangres** [hawariyaa/lab1#2]
add more code.

**Comment by hawariyaa** [comment]
like what

**Comment by astalangres** [comment]
like i dont know more elaborative code and add more comments to describe each code it looks bezare.

**Comment by hawariyaa** [comment]
does it look out of context and hard to understand?

**Comment by astalangres** [comment]
yap so divide the code and in between the code use comments to describe your code

**Comment by hawariyaa** [comment]
ok
